feature/payload-validation
truvami/decoder pull request #23
Opened 2024-12-20 09:14 UTC by simylein

2024-12-20 15:00 UTC, michaelbeutler requested changes

2024-12-20 15:02 UTC, simylein commented on cmd/root.go
> +	rootCmd.PersistentFlags().BoolVarP(&SkipValidation, "skip-validation", "", false, "Skip length validation of payload. (default: false)")
Currently, this only affects the hard errors, and not the "soft" warnings.

2025-01-08 12:37 UTC, simylein commented
Now the question becomes what happens to our http server. 
currently it returns
```
HTTP/1.1 400 Bad Request
payloadtooshort
```
```
HTTP/1.1 400 Bad Request
payloadtoolong
```
and for success
```
HTTP/1.1 200 OK
{
	"data": {
		"lowBattery": false,
		"battery": 3.67
	},
	"metadata": {
		"dutyCycle": false,
		"configChangeId": 0,
		"configChangeSuccess": false,
		"moving": false
	}
}
```
So we need a way to indicate any soft warnings which do not stop the decode from happening to the client. 
I would propose adding a warnings field like this only if at least one of the validations fail. 
```
HTTP/1.1 200 OK
{
	"data": {
		"lowBattery": false,
		"battery": 7.67
	},
	"metadata": {
		"dutyCycle": false,
		"configChangeId": 0,
		"configChangeSuccess": false,
		"moving": false
	},
	"warnings": [
		"Key: 'Battery' Error:Field validation for 'Battery' failed on the 'lte' tag"
	]
}
```

2025-01-10 15:07 UTC, simylein commented
Pull request is ready, please let me know what you think @michaelbeutler 
The http server looks like this:
<img width="311" alt="Screenshot 2025-01-10 at 16 06 50" src="https://github.com/user-attachments/assets/548244b0-9b0a-4265-b227-6a895ee56659" />
<img width="353" alt="Screenshot 2025-01-10 at 16 07 21" src="https://github.com/user-attachments/assets/e857662b-5500-4f12-871e-14558163a673" />

2025-01-10 15:40 UTC, michaelbeutler commented
How does the hard error look like?

2025-01-13 15:52 UTC, michaelbeutler requested changes
Please add the validation to the new `smartlabel` decoder as well. The HTTP response for “hard” errors isn't enough yet. (see comments).

Overall a good PR, looking forward to approving after the small adjustments.

2025-01-13 15:52 UTC, michaelbeutler commented on cmd/http.go
>  				loracloud.NewLoracloudMiddleware(accessToken),
`WithSkipValidation` has not been called.

```go
smartlabel.WithSkipValidation(SkipValidation)

2025-01-13 15:52 UTC, michaelbeutler commented on cmd/http.go
> +				setHeaders(w, http.StatusBadRequest)
Set the `Content-Type` to `application/problem+json` to indicate an error.

2025-01-13 15:52 UTC, michaelbeutler commented on cmd/http.go
> +				_, err = w.Write([]byte(err.Error()))
Please return a proper JSON response like:
```json
{
    "error": "payload too short",
    "traceId": "ae24cfe0-85c3-4aab-8ead-a1ece803dc88",
    "docs": "https://docs.truvami.com"
}
```

The `traceId` can be randomly generated, I suggest using the `github.com/google/uuid` module.`docs` link can be static as of now.

2025-01-13 16:28 UTC, simylein commented on cmd/http.go
> +				_, err = w.Write([]byte(err.Error()))
We are already sending `x-request-id: random-uuid` as a header to the client. 
I suggest keeping that, as in my opinion trace ids belong in the header of responses. 
And since we are already logging this, we can `trace` an individual request and therefore response.

2025-01-13 16:47 UTC, simylein commented on cmd/http.go
> +				_, err = w.Write([]byte(err.Error()))
We are now sending json in error cases:
<img width="459" alt="Screenshot 2025-01-13 at 17 45 55" src="https://github.com/user-attachments/assets/d1fada59-d771-46a4-a33f-c3be5339aa66" />
<img width="461" alt="Screenshot 2025-01-13 at 17 46 04" src="https://github.com/user-attachments/assets/ebb6a99c-6f1b-4a93-857d-51ffc9f5afd5" />
<img width="461" alt="Screenshot 2025-01-13 at 17 46 13" src="https://github.com/user-attachments/assets/8915f766-c5ef-458d-aeff-f0f529fd19f0" />

2025-01-13 22:22 UTC, michaelbeutler approved these changes

2025-01-13 22:22 UTC, merged